allowBuilds:
  esbuild: true
  sharp: true
  "@electric-sql/pglite": true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.17'
  - '@better-auth/drizzle-adapter@1.6.17'
  - '@better-auth/kysely-adapter@1.6.17'
  - '@better-auth/memory-adapter@1.6.17'
  - '@better-auth/mongo-adapter@1.6.17'
  - '@better-auth/prisma-adapter@1.6.17'
  - '@better-auth/telemetry@1.6.17'
  - better-auth@1.6.17
